"""Fontes autorais do universo de Corner Office (Game Design Bible §§2–3, 13–14).

Tudo aqui é fictício: organizações, arenas, comissões, lutadores históricos e
eventos. Países e cidades são reais só como geografia. Nada de UFC, ONE, PFL,
Bellator, RIZIN, pessoas reais ou nomes de eventos reais (CLAUDE.md).

`tools/build_universe.py` lê este arquivo e grava `game/content/universe/*.json`.
"""

# ---------------------------------------------------------------------------
# Macro-regiões do universo. `game_region` liga ao id de content/regions.json
# quando existe (a simulação atual só conhece essas oito).
# ---------------------------------------------------------------------------
REGIONS = [
    ("brazil", "Brasil", "brazil", "O celeiro. Academias de BJJ em cada bairro, vale-tudo no DNA e prospects saindo aos montes."),
    ("north_america", "América do Norte", "usa", "O maior mercado do planeta: wrestling universitário, PPV e academias-empresa."),
    ("mexico", "México", "mexico", "Cultura de boxe, torcida fervorosa e noites de arena lotada."),
    ("latam", "América Latina", None, "Cenas nacionais pequenas, mas famintas; muitos atletas migram para o Brasil e os EUA."),
    ("europe_west", "Europa Ocidental", "europe", "Kickboxing holandês, circuitos britânicos e mercados que cresceram com a regulamentação."),
    ("europe_east", "Europa Oriental e Bálcãs", "europe", "Atletas duros, sambo, kickboxing e ginásios lotados por orgulho nacional."),
    ("central_asia", "Cáucaso e Ásia Central", "central_asia", "Wrestling desde a infância, sambo e grappling de controle; pouco marketing, muita técnica."),
    ("japan_korea", "Japão e Coreia", "japan_korea", "Ringues, Grand Prix, tradição de megaeventos e artes marciais clássicas."),
    ("asia_pacific", "Sudeste Asiático e China", None, "Mercado novo, grandes audiências digitais, muay thai e sanda."),
    ("oceania", "Oceania", "oceania", "Hub do Pacífico, preparação física de elite e mercado organizado."),
    ("middle_east", "Oriente Médio", "middle_east", "Capital, eventos especiais, garantias altas e cidades-vitrine."),
    ("africa", "África", None, "Talento atlético bruto, diáspora forte e cenas nacionais nascendo."),
]

# iso, nome, região, cena(0-100), mercado(0-100), paixão(0-100), estilos,
# comissão fictícia, capital, moeda
COUNTRIES = [
    ("BR", "Brasil", "brazil", 92, 62, 95, ["bjj", "muay_thai", "boxing"], "Conselho Nacional de Lutas (CNL)", "Brasília", "BRL"),
    ("US", "Estados Unidos", "north_america", 97, 100, 80, ["wrestling", "boxing", "complete"], "comissões atléticas estaduais", "Washington", "USD"),
    ("CA", "Canadá", "north_america", 70, 68, 72, ["wrestling", "karate", "complete"], "comissões provinciais", "Ottawa", "CAD"),
    ("MX", "México", "mexico", 74, 60, 92, ["boxing", "pressure", "cardio"], "Comisión Nacional de Box y Lucha (CNBL)", "Cidade do México", "MXN"),
    ("AR", "Argentina", "latam", 48, 35, 78, ["boxing", "bjj"], "Ente Federal de Deportes de Combate", "Buenos Aires", "ARS"),
    ("CL", "Chile", "latam", 38, 28, 62, ["kickboxing", "bjj"], "Federación Chilena de Artes Marciales Mixtas", "Santiago", "CLP"),
    ("CO", "Colômbia", "latam", 36, 30, 70, ["boxing", "wrestling"], "Coldeportes Combate", "Bogotá", "COP"),
    ("PE", "Peru", "latam", 42, 24, 74, ["bjj", "wrestling"], "Comisión Peruana de Combate", "Lima", "PEN"),
    ("CU", "Cuba", "latam", 40, 8, 70, ["wrestling", "boxing", "judo"], "INDER (sem MMA profissional doméstico)", "Havana", "CUP"),
    ("GB", "Reino Unido", "europe_west", 80, 78, 82, ["striking", "conditioning", "boxing"], "British Combat Sports Board (BCSB)", "Londres", "GBP"),
    ("IE", "Irlanda", "europe_west", 66, 42, 90, ["boxing", "striking"], "Irish Combat Standards Council", "Dublin", "EUR"),
    ("FR", "França", "europe_west", 64, 64, 66, ["kickboxing", "judo", "wrestling"], "Fédération Française de MMA (FFMMA)", "Paris", "EUR"),
    ("DE", "Alemanha", "europe_west", 60, 70, 55, ["kickboxing", "wrestling"], "Deutscher Kampfsportrat", "Berlim", "EUR"),
    ("NL", "Países Baixos", "europe_west", 72, 52, 70, ["kickboxing", "muay_thai"], "Nederlandse Vechtsportautoriteit", "Amsterdã", "EUR"),
    ("BE", "Bélgica", "europe_west", 46, 40, 55, ["kickboxing", "judo"], "Conseil Belge des Sports de Combat", "Bruxelas", "EUR"),
    ("ES", "Espanha", "europe_west", 52, 55, 64, ["kickboxing", "bjj"], "Consejo Español de Deportes de Contacto", "Madri", "EUR"),
    ("PT", "Portugal", "europe_west", 44, 32, 66, ["bjj", "kickboxing"], "Federação Portuguesa de Combate", "Lisboa", "EUR"),
    ("IT", "Itália", "europe_west", 48, 55, 60, ["kickboxing", "boxing"], "Federazione Italiana Sport da Combattimento", "Roma", "EUR"),
    ("SE", "Suécia", "europe_west", 58, 48, 58, ["striking", "grappling"], "Svenska Kampsportsnämnden", "Estocolmo", "SEK"),
    ("NO", "Noruega", "europe_west", 34, 44, 50, ["grappling"], "sem sancionamento profissional até 2021", "Oslo", "NOK"),
    ("DK", "Dinamarca", "europe_west", 40, 40, 52, ["striking"], "Dansk Kampsportsråd", "Copenhague", "DKK"),
    ("PL", "Polônia", "europe_east", 76, 58, 90, ["kickboxing", "wrestling", "boxing"], "Polska Rada Sportów Walki", "Varsóvia", "PLN"),
    ("CZ", "Tchéquia", "europe_east", 55, 40, 74, ["kickboxing", "wrestling"], "Česká Komise Bojových Sportů", "Praga", "CZK"),
    ("RS", "Sérvia", "europe_east", 60, 30, 82, ["wrestling", "kickboxing"], "Srpski Savez Borilačkih Sportova", "Belgrado", "RSD"),
    ("HR", "Croácia", "europe_east", 58, 30, 80, ["kickboxing", "striking"], "Hrvatski Savez Borilačkih Vještina", "Zagreb", "EUR"),
    ("BA", "Bósnia e Herzegovina", "europe_east", 42, 12, 78, ["kickboxing", "wrestling"], "Savez Borilačkih Sportova BiH", "Sarajevo", "BAM"),
    ("RO", "Romênia", "europe_east", 44, 30, 66, ["kickboxing", "wrestling"], "Federația Română de Sporturi de Contact", "Bucareste", "RON"),
    ("BG", "Bulgária", "europe_east", 42, 20, 64, ["wrestling", "sambo"], "Balgarski Savet po Borbi", "Sófia", "BGN"),
    ("GR", "Grécia", "europe_east", 38, 26, 60, ["wrestling", "kickboxing"], "Elliniki Epitropi Machitikon", "Atenas", "EUR"),
    ("UA", "Ucrânia", "europe_east", 62, 26, 70, ["wrestling", "sambo", "boxing"], "Federação Ucraniana de Combate", "Kiev", "UAH"),
    ("RU", "Rússia", "central_asia", 88, 55, 72, ["sambo", "wrestling", "combat_sambo"], "Federação Russa de Artes Marciais Mistas", "Moscou", "RUB"),
    ("GE", "Geórgia", "central_asia", 64, 14, 84, ["wrestling", "judo", "sambo"], "Conselho Georgiano de Combate", "Tbilisi", "GEL"),
    ("AM", "Armênia", "central_asia", 54, 12, 82, ["wrestling", "boxing"], "Federação Armênia de Combate", "Erevan", "AMD"),
    ("AZ", "Azerbaijão", "central_asia", 55, 26, 78, ["wrestling", "sambo"], "Federação Azerbaijana de Combate", "Baku", "AZN"),
    ("KZ", "Cazaquistão", "central_asia", 72, 36, 80, ["wrestling", "sambo", "boxing"], "Comitê Cazaque de Esportes de Combate", "Astana", "KZT"),
    ("KG", "Quirguistão", "central_asia", 56, 10, 82, ["wrestling", "kickboxing"], "Federação Quirguiz de MMA", "Bishkek", "KGS"),
    ("UZ", "Uzbequistão", "central_asia", 58, 20, 78, ["wrestling", "sambo", "judo"], "Comitê Uzbeque de Combate", "Tashkent", "UZS"),
    ("TJ", "Tadjiquistão", "central_asia", 48, 6, 76, ["wrestling", "sambo"], "Federação Tadjique de Combate", "Duchambé", "TJS"),
    ("TR", "Turquia", "europe_east", 46, 44, 72, ["wrestling", "kickboxing"], "Türkiye Dövüş Sporları Kurulu", "Ancara", "TRY"),
    ("IR", "Irã", "middle_east", 40, 12, 70, ["wrestling"], "sem liga profissional reconhecida", "Teerã", "IRR"),
    ("AE", "Emirados Árabes Unidos", "middle_east", 58, 80, 50, ["bjj"], "Autoridade de Esportes de Combate dos Emirados", "Abu Dhabi", "AED"),
    ("SA", "Arábia Saudita", "middle_east", 36, 82, 52, [], "Comissão Saudita de Eventos de Combate", "Riad", "SAR"),
    ("QA", "Catar", "middle_east", 24, 70, 40, [], "Autoridade Catari de Eventos", "Doha", "QAR"),
    ("BH", "Barein", "middle_east", 38, 50, 48, [], "Comissão de Combate do Barein", "Manama", "BHD"),
    ("EG", "Egito", "africa", 34, 22, 66, ["wrestling", "karate"], "Federação Egípcia de Combate", "Cairo", "EGP"),
    ("MA", "Marrocos", "africa", 40, 22, 70, ["kickboxing", "boxing"], "Fédération Royale de Sports de Combat", "Rabat", "MAD"),
    ("NG", "Nigéria", "africa", 46, 26, 76, ["wrestling", "boxing"], "Nigeria Combat Sports Commission", "Abuja", "NGN"),
    ("CM", "Camarões", "africa", 44, 10, 74, ["wrestling", "judo"], "Fédération Camerounaise de Combat", "Iaundé", "XAF"),
    ("ZA", "África do Sul", "africa", 50, 34, 64, ["wrestling", "kickboxing"], "South African Combat Board", "Pretória", "ZAR"),
    ("JP", "Japão", "japan_korea", 82, 76, 76, ["judo", "karate", "kickboxing"], "Japan Combat Sports Commission (JCSC)", "Tóquio", "JPY"),
    ("KR", "Coreia do Sul", "japan_korea", 64, 52, 66, ["taekwondo", "judo", "kickboxing"], "Korea Combat Sports Council", "Seul", "KRW"),
    ("CN", "China", "asia_pacific", 60, 74, 58, ["sanda", "wrestling"], "Associação Chinesa de Artes Marciais Mistas", "Pequim", "CNY"),
    ("MN", "Mongólia", "asia_pacific", 44, 6, 80, ["wrestling", "judo"], "Federação Mongol de Combate", "Ulan Bator", "MNT"),
    ("PH", "Filipinas", "asia_pacific", 50, 30, 84, ["wushu", "boxing"], "Games and Amusements Combat Unit", "Manila", "PHP"),
    ("TH", "Tailândia", "asia_pacific", 60, 36, 86, ["muay_thai"], "Thai Combat Sports Authority", "Bangkok", "THB"),
    ("ID", "Indonésia", "asia_pacific", 40, 34, 70, ["silat", "wrestling"], "Komisi Tarung Indonesia", "Jacarta", "IDR"),
    ("IN", "Índia", "asia_pacific", 38, 50, 60, ["wrestling"], "Indian Combat Sports Federation", "Nova Délhi", "INR"),
    ("SG", "Singapura", "asia_pacific", 48, 58, 50, ["complete"], "Singapore Combat Sports Council", "Singapura", "SGD"),
    ("MC", "Mônaco", "europe_west", 20, 60, 40, [], "Direction des Sports de Monaco", "Mônaco", "EUR"),
    ("AU", "Austrália", "oceania", 74, 70, 76, ["striking", "conditioning", "wrestling"], "Australian Combat Sports Commission", "Camberra", "AUD"),
    ("NZ", "Nova Zelândia", "oceania", 62, 36, 74, ["kickboxing", "striking"], "NZ Combat Sports Authority", "Wellington", "NZD"),
]

# cidade, país, mercado(0-100), paixão(0-100), nota
CITIES = [
    ("Las Vegas", "US", 100, 82, "Capital mundial das lutas; hotéis-cassino disputam as grandes noites."),
    ("Los Angeles", "US", 92, 70, "Sede da Ascend; Hollywood e streaming."),
    ("Nova York", "US", 96, 76, "Mercado liberado só em 2016 depois de uma longa batalha legislativa."),
    ("Newark", "US", 74, 78, "Arena do outro lado do rio, ponte para o público de Nova York."),
    ("Chicago", "US", 80, 74, "Coração do Meio-Oeste e do wrestling colegial."),
    ("Houston", "US", 82, 78, "Grande público latino e texano."),
    ("Dallas", "US", 80, 74, "Estádios gigantes e cultura de espetáculo."),
    ("Miami", "US", 78, 80, "Porta de entrada para latinos e brasileiros."),
    ("Phoenix", "US", 66, 70, "Deserto, academias de wrestling e custo baixo."),
    ("Denver", "US", 62, 68, "Altitude: o cardio decide lutas aqui."),
    ("Seattle", "US", 66, 64, "Cena alternativa e academias técnicas."),
    ("Atlanta", "US", 72, 76, "Mercado em alta e produção audiovisual."),
    ("Boston", "US", 70, 80, "Público fanático e duro com favoritos."),
    ("Filadélfia", "US", 68, 82, "Tradição de boxe e vaias históricas."),
    ("Salt Lake City", "US", 50, 60, "Arena média com público fiel."),
    ("Albuquerque", "US", 44, 66, "Altitude e uma das academias mais famosas do deserto."),
    ("Honolulu", "US", 42, 88, "Ilha pequena, orgulho enorme."),
    ("Atlantic City", "US", 58, 70, "Cidade-cassino da Costa Leste; casa da extinta Atlantic Fight League."),
    ("Montreal", "CA", 74, 88, "A cidade mais apaixonada da América do Norte."),
    ("Toronto", "CA", 78, 76, "Maior mercado canadense."),
    ("Vancouver", "CA", 60, 66, "Porta para o Pacífico."),
    ("Edmonton", "CA", 44, 70, "Frio lá fora, ginásio fervendo."),
    ("São Paulo", "BR", 90, 88, "Sede da Vale; o maior mercado da América do Sul."),
    ("Rio de Janeiro", "BR", 86, 96, "Berço do vale-tudo; a torcida mais barulhenta do mundo."),
    ("Belo Horizonte", "BR", 62, 86, "Academias tradicionais e escola de muay thai."),
    ("Curitiba", "BR", 60, 90, "Terra de academias lendárias de muay thai."),
    ("Porto Alegre", "BR", 56, 84, "Circuito gaúcho duro e frio."),
    ("Salvador", "BR", 54, 88, "Capoeira, BJJ e noites cheias."),
    ("Recife", "BR", 50, 92, "Nordeste fervendo e prospects famintos."),
    ("Fortaleza", "BR", 50, 90, "Terra de strikers agressivos."),
    ("Manaus", "BR", 44, 90, "Grappling e resistência no calor amazônico."),
    ("Belém", "BR", 40, 88, "Tradição de lutadores do Norte."),
    ("Goiânia", "BR", 42, 80, "Centro-Oeste em crescimento."),
    ("Florianópolis", "BR", 48, 76, "Academias de praia e turismo."),
    ("Brasília", "BR", 52, 72, "Ginásio grande e patrocínio público."),
    ("Natal", "BR", 38, 88, "Nordeste que exporta talento."),
    ("Cidade do México", "MX", 88, 94, "Arena gigante e fãs que cantam o nome do ídolo."),
    ("Monterrey", "MX", 70, 90, "Norte industrial, torcida brava."),
    ("Guadalajara", "MX", 68, 92, "Boxe no sangue."),
    ("Tijuana", "MX", 58, 90, "Fronteira e academias de cardio."),
    ("Buenos Aires", "AR", 70, 84, "Tradição de boxe e público exigente."),
    ("Córdoba", "AR", 40, 78, "Circuito argentino do interior."),
    ("Santiago", "CL", 56, 66, "Cena chilena em crescimento."),
    ("Bogotá", "CO", 58, 72, "Altitude e mercado emergente."),
    ("Medellín", "CO", 48, 78, "Academias novas e ambição."),
    ("Lima", "PE", 54, 80, "O Peru virou fábrica de grapplers."),
    ("Londres", "GB", 94, 80, "Sede da Frontline; o centro europeu das lutas."),
    ("Manchester", "GB", 72, 88, "Norte inglês barulhento."),
    ("Liverpool", "GB", 64, 90, "Torcida apaixonada e academias de boxe."),
    ("Birmingham", "GB", 62, 76, "Arena central e público fiel."),
    ("Glasgow", "GB", 56, 90, "A arena mais barulhenta da Grã-Bretanha."),
    ("Cardiff", "GB", 48, 84, "Orgulho galês."),
    ("Newcastle", "GB", 50, 82, "Circuito do nordeste inglês."),
    ("Dublin", "IE", 70, 96, "Uma ilha inteira atrás de seu lutador."),
    ("Belfast", "GB", 46, 88, "Pequena e intensa."),
    ("Paris", "FR", 88, 70, "Mercado liberado só em 2020; público novo e enorme."),
    ("Marselha", "FR", 56, 84, "Sul francês, muay thai e boxe."),
    ("Lyon", "FR", 52, 66, "Academias técnicas de judô."),
    ("Berlim", "DE", 72, 60, "Capital com arena moderna."),
    ("Colônia", "DE", 64, 62, "Arena grande do Reno."),
    ("Hamburgo", "DE", 60, 62, "Porto do norte alemão."),
    ("Munique", "DE", 62, 56, "Mercado rico e contido."),
    ("Amsterdã", "NL", 72, 74, "Capital do kickboxing mundial."),
    ("Roterdã", "NL", 54, 74, "Porto e academias de chute."),
    ("Bruxelas", "BE", 54, 56, "Centro burocrático, público misto."),
    ("Antuérpia", "BE", 46, 60, "Cena flamenga de kickboxing."),
    ("Madri", "ES", 70, 66, "Capital espanhola, arena grande."),
    ("Barcelona", "ES", 72, 64, "Turismo e público internacional."),
    ("Lisboa", "PT", 58, 70, "Ponte entre Brasil e Europa."),
    ("Porto", "PT", 44, 72, "Circuito nortenho."),
    ("Milão", "IT", 68, 60, "Moda, dinheiro e noites de gala."),
    ("Roma", "IT", 66, 64, "Coliseus modernos."),
    ("Estocolmo", "SE", 64, 64, "Maior cena nórdica."),
    ("Gotemburgo", "SE", 46, 62, "Academias de grappling."),
    ("Oslo", "NO", 50, 50, "Mercado novo desde 2021."),
    ("Copenhague", "DK", 54, 56, "Arena escandinava moderna."),
    ("Varsóvia", "PL", 74, 90, "Estádio lotado para lutas; febre nacional."),
    ("Cracóvia", "PL", 62, 90, "Uma das maiores arenas cobertas da Europa."),
    ("Gdańsk", "PL", 52, 88, "Costa báltica fervendo."),
    ("Łódź", "PL", 50, 86, "Arena média e público fiel."),
    ("Praga", "CZ", 60, 78, "Nova potência da Europa Central."),
    ("Belgrado", "RS", 56, 88, "Orgulho balcânico."),
    ("Zagreb", "HR", 54, 86, "Tradição de kickboxing."),
    ("Sarajevo", "BA", 36, 86, "Pequena e barulhenta."),
    ("Bucareste", "RO", 48, 70, "Kickboxing e público crescente."),
    ("Sófia", "BG", 40, 68, "Wrestling e sambo."),
    ("Atenas", "GR", 46, 66, "Pancrácio moderno."),
    ("Kiev", "UA", 50, 68, "Cena técnica e resiliente."),
    ("Istambul", "TR", 72, 76, "Ponte entre Europa e Ásia."),
    ("Moscou", "RU", 82, 70, "Maior mercado do Leste."),
    ("São Petersburgo", "RU", 66, 68, "Academias de sambo e judô."),
    ("Makhachkala", "RU", 40, 98, "Wrestling é religião; a fábrica de campeões do Cáucaso."),
    ("Grozny", "RU", 38, 90, "Arena nova e academias disciplinadas."),
    ("Kazan", "RU", 50, 70, "Centro esportivo do Volga."),
    ("Tbilisi", "GE", 44, 88, "Wrestlers e judocas de elite."),
    ("Erevan", "AM", 38, 86, "Diáspora grande e apaixonada."),
    ("Baku", "AZ", 54, 76, "Capital rica e arena olímpica."),
    ("Almaty", "KZ", 66, 84, "Sede da Iron Circle; montanhas e wrestling."),
    ("Astana", "KZ", 60, 72, "Capital futurista com arena coberta."),
    ("Bishkek", "KG", 34, 88, "Pequena e intensa."),
    ("Tashkent", "UZ", 50, 80, "Wrestling, judô e sambo."),
    ("Duchambé", "TJ", 26, 80, "Mercado minúsculo, talentos enormes."),
    ("Teerã", "IR", 40, 74, "Wrestlers de elite sem liga profissional."),
    ("Abu Dhabi", "AE", 82, 50, "Ilhas-arena, garantias altas e grappling."),
    ("Dubai", "AE", 84, 52, "Cidade-vitrine e eventos de gala."),
    ("Riad", "SA", 86, 56, "Capital que compra megaeventos."),
    ("Doha", "QA", 70, 44, "Arena de luxo e agenda esporádica."),
    ("Manama", "BH", 56, 54, "Pequena ilha com promoção própria."),
    ("Cairo", "EG", 50, 66, "Mercado árabe grande e jovem."),
    ("Casablanca", "MA", 48, 72, "Kickboxing marroquino e diáspora europeia."),
    ("Lagos", "NG", 56, 80, "Megacidade e diáspora nigeriana."),
    ("Iaundé", "CM", 28, 76, "Wrestlers poderosos e poucos eventos."),
    ("Joanesburgo", "ZA", 58, 70, "Maior cena africana organizada."),
    ("Cidade do Cabo", "ZA", 50, 66, "Turismo e academias técnicas."),
    ("Tóquio", "JP", 94, 76, "Sede da Shinsei; noites de réveillon históricas."),
    ("Osaka", "JP", 76, 80, "Kansai barulhento e ringues tradicionais."),
    ("Saitama", "JP", 70, 82, "A arena dos grandes Grand Prix."),
    ("Nagoya", "JP", 58, 70, "Centro industrial e dojôs de judô."),
    ("Fukuoka", "JP", 52, 74, "Kyushu e porta para a Coreia."),
    ("Sapporo", "JP", 46, 66, "Norte gelado, público fiel."),
    ("Seul", "KR", 76, 70, "Mercado digital e taekwondo."),
    ("Busan", "KR", 52, 74, "Porto e academias de striking."),
    ("Xangai", "CN", 82, 58, "Arena moderna e audiência digital gigante."),
    ("Pequim", "CN", 78, 56, "Capital e sanda."),
    ("Chengdu", "CN", 56, 62, "Oeste chinês em crescimento."),
    ("Shenzhen", "CN", 70, 52, "Dinheiro de tecnologia."),
    ("Ulan Bator", "MN", 28, 88, "Wrestling tradicional."),
    ("Manila", "PH", 62, 90, "Ídolos nacionais e torcida enorme."),
    ("Baguio", "PH", 30, 88, "Montanha que forja wushu e resistência."),
    ("Bangkok", "TH", 72, 88, "Muay thai em cada esquina."),
    ("Phuket", "TH", 42, 70, "Campos de treino para estrangeiros."),
    ("Jacarta", "ID", 60, 72, "Mercado grande e jovem."),
    ("Singapura", "SG", 74, 54, "Hub asiático, produção de TV."),
    ("Mumbai", "IN", 62, 60, "Mercado gigante ainda adormecido."),
    ("Nova Délhi", "IN", 58, 62, "Wrestling tradicional (kushti)."),
    ("Mônaco", "MC", 60, 40, "Principado de luxo; sede da extinta Riviera Fight Club."),
    ("Sydney", "AU", 84, 76, "Sede da Pacific Fight League."),
    ("Melbourne", "AU", 78, 82, "Arena de estádio e público gigante."),
    ("Brisbane", "AU", 60, 76, "Queensland e academias de preparação física."),
    ("Perth", "AU", 54, 78, "Oeste isolado, arena cheia."),
    ("Adelaide", "AU", 44, 68, "Cena pequena e organizada."),
    ("Auckland", "NZ", 62, 84, "A cidade que produz campeões de striking."),
    ("Christchurch", "NZ", 36, 74, "Circuito sul-neozelandês."),
]

# arena, cidade, capacidade, nível (clube|ginásio|arena|estádio), custo-base/noite (USD)
VENUES = [
    ("Desert Diamond Pavilion", "Las Vegas", 20000, "arena", 900000),
    ("Mirage Row Events Center", "Las Vegas", 12000, "arena", 520000),
    ("Neon Hall", "Las Vegas", 3200, "ginásio", 70000),
    ("Sunset Strip Garden", "Los Angeles", 18000, "arena", 780000),
    ("Harbor Grand Arena", "Los Angeles", 14000, "arena", 480000),
    ("Echo Park Fight Hall", "Los Angeles", 1400, "clube", 18000),
    ("Hudson Square Garden", "Nova York", 19500, "arena", 1100000),
    ("Queens Armory", "Nova York", 5000, "ginásio", 120000),
    ("Ironbound Center", "Newark", 16000, "arena", 420000),
    ("Lakefront Dome", "Chicago", 21000, "arena", 620000),
    ("Bayou City Coliseum", "Houston", 18000, "arena", 460000),
    ("Lone Star Stadium", "Dallas", 72000, "estádio", 2600000),
    ("Biscayne Arena", "Miami", 19000, "arena", 540000),
    ("Copper Canyon Arena", "Phoenix", 16000, "arena", 360000),
    ("Mile High Pavilion", "Denver", 17000, "arena", 380000),
    ("Emerald Hall", "Seattle", 14000, "arena", 320000),
    ("Peachtree Dome", "Atlanta", 18000, "arena", 420000),
    ("Harborside Garden", "Boston", 17500, "arena", 480000),
    ("Liberty Bell Arena", "Filadélfia", 19000, "arena", 440000),
    ("Wasatch Center", "Salt Lake City", 15000, "arena", 280000),
    ("Rio Grande Hall", "Albuquerque", 6000, "ginásio", 90000),
    ("Aloha Coliseum", "Honolulu", 9000, "ginásio", 160000),
    ("Centre Saint-Laurent", "Montreal", 21000, "arena", 520000),
    ("Lakeshore Arena", "Toronto", 19000, "arena", 560000),
    ("Coastline Arena", "Vancouver", 17000, "arena", 380000),
    ("Northern Lights Coliseum", "Edmonton", 17000, "arena", 300000),
    ("Arena Paulista", "São Paulo", 16000, "arena", 380000),
    ("Ginásio do Anhangabaú", "São Paulo", 10000, "ginásio", 160000),
    ("Estádio da Várzea", "São Paulo", 45000, "estádio", 1300000),
    ("Galpão da Mooca", "São Paulo", 1500, "clube", 16000),
    ("Arena Guanabara", "Rio de Janeiro", 15000, "arena", 360000),
    ("Ginásio do Maracá", "Rio de Janeiro", 11000, "ginásio", 190000),
    ("Clube Tijuca Combate", "Rio de Janeiro", 1800, "clube", 20000),
    ("Arena das Gerais", "Belo Horizonte", 12000, "arena", 220000),
    ("Ginásio Araucária", "Curitiba", 9000, "ginásio", 140000),
    ("Arena Guaíba", "Porto Alegre", 10000, "arena", 170000),
    ("Arena Fonte Nova do Combate", "Salvador", 11000, "arena", 180000),
    ("Ginásio Capibaribe", "Recife", 8000, "ginásio", 110000),
    ("Arena Iracema", "Fortaleza", 9000, "ginásio", 120000),
    ("Arena Rio Negro", "Manaus", 8000, "ginásio", 110000),
    ("Ginásio Ver-o-Peso", "Belém", 6000, "ginásio", 80000),
    ("Arena Cerrado", "Goiânia", 8000, "ginásio", 100000),
    ("Ginásio da Ilha", "Florianópolis", 6000, "ginásio", 90000),
    ("Arena Planalto", "Brasília", 14000, "arena", 240000),
    ("Ginásio Potengi", "Natal", 5000, "ginásio", 60000),
    ("Arena Tenochtitlan", "Cidade do México", 22000, "arena", 520000),
    ("Palacio de los Puños", "Cidade do México", 9000, "ginásio", 150000),
    ("Arena Sierra Madre", "Monterrey", 17000, "arena", 320000),
    ("Arena Tapatía", "Guadalajara", 14000, "arena", 260000),
    ("Auditorio Frontera", "Tijuana", 7000, "ginásio", 90000),
    ("Estadio Río de la Plata Cubierto", "Buenos Aires", 15000, "arena", 260000),
    ("Arena Mediterránea", "Córdoba", 6000, "ginásio", 70000),
    ("Arena Andes", "Santiago", 12000, "arena", 180000),
    ("Coliseo El Dorado", "Bogotá", 14000, "arena", 180000),
    ("Arena Antioquia", "Medellín", 8000, "ginásio", 100000),
    ("Coliseo del Pacífico", "Lima", 10000, "arena", 140000),
    ("Thameside Arena", "Londres", 20000, "arena", 820000),
    ("Victoria Dock Hall", "Londres", 8000, "ginásio", 190000),
    ("Old Kent Road Club", "Londres", 1200, "clube", 22000),
    ("Irwell Arena", "Manchester", 21000, "arena", 460000),
    ("Mersey Pavilion", "Liverpool", 11000, "arena", 220000),
    ("Bullring Hall", "Birmingham", 15000, "arena", 280000),
    ("Clydeside Hydro Hall", "Glasgow", 13000, "arena", 260000),
    ("Taff Arena", "Cardiff", 7500, "ginásio", 120000),
    ("Tyne Arena", "Newcastle", 11000, "arena", 200000),
    ("Liffey Arena", "Dublin", 13000, "arena", 300000),
    ("Lagan Dome", "Belfast", 10000, "arena", 180000),
    ("Palais de la Seine", "Paris", 20000, "arena", 640000),
    ("Salle Vieux-Port", "Marselha", 8500, "ginásio", 140000),
    ("Halle Rhône", "Lyon", 9000, "ginásio", 140000),
    ("Spree Arena", "Berlim", 17000, "arena", 380000),
    ("Rheinhalle", "Colônia", 18000, "arena", 360000),
    ("Elbe Dome", "Hamburgo", 13000, "arena", 280000),
    ("Isar Halle", "Munique", 12000, "arena", 280000),
    ("Amstel Dome", "Amsterdã", 17000, "arena", 380000),
    ("Maashaven Hall", "Roterdã", 11000, "arena", 200000),
    ("Palais Atomium", "Bruxelas", 12000, "arena", 220000),
    ("Scheldt Arena", "Antuérpia", 16000, "arena", 240000),
    ("Palacio Castellana", "Madri", 15000, "arena", 320000),
    ("Palau Montjuïc", "Barcelona", 16000, "arena", 340000),
    ("Pavilhão do Tejo", "Lisboa", 12000, "arena", 200000),
    ("Arena Douro", "Porto", 8000, "ginásio", 110000),
    ("Arena Navigli", "Milão", 12000, "arena", 260000),
    ("Palazzo Tevere", "Roma", 11000, "arena", 240000),
    ("Mälaren Arena", "Estocolmo", 16000, "arena", 320000),
    ("Göta Hall", "Gotemburgo", 11000, "arena", 180000),
    ("Fjord Arena", "Oslo", 9000, "ginásio", 170000),
    ("Øresund Arena", "Copenhague", 12000, "arena", 220000),
    ("Arena Narodowa Wisła", "Varsóvia", 58000, "estádio", 1400000),
    ("Hala Mazowsze", "Varsóvia", 11000, "arena", 180000),
    ("Arena Wawel", "Cracóvia", 18000, "arena", 300000),
    ("Hala Bałtycka", "Gdańsk", 11000, "arena", 180000),
    ("Hala Włókniarzy", "Łódź", 13000, "arena", 180000),
    ("Vltava Arena", "Praga", 17000, "arena", 300000),
    ("Hala Kalemegdan", "Belgrado", 18000, "arena", 240000),
    ("Dvorana Sava", "Zagreb", 15000, "arena", 220000),
    ("Dvorana Miljacka", "Sarajevo", 6000, "ginásio", 60000),
    ("Sala Dâmbovița", "Bucareste", 10000, "arena", 140000),
    ("Arena Vitosha", "Sófia", 12000, "arena", 140000),
    ("Pankration Hall", "Atenas", 14000, "arena", 180000),
    ("Palats Dnipro", "Kiev", 7000, "ginásio", 90000),
    ("Bosphorus Arena", "Istambul", 16000, "arena", 300000),
    ("Arena Moskva-Reka", "Moscou", 22000, "arena", 480000),
    ("Neva Sports Palace", "São Petersburgo", 12000, "arena", 220000),
    ("Arena Tarki-Tau", "Makhachkala", 7000, "ginásio", 80000),
    ("Arena Terek", "Grozny", 10000, "arena", 140000),
    ("Kazanka Hall", "Kazan", 9000, "ginásio", 120000),
    ("Mtkvari Arena", "Tbilisi", 10000, "arena", 120000),
    ("Ararat Hall", "Erevan", 7000, "ginásio", 80000),
    ("Caspian Crystal Hall", "Baku", 25000, "arena", 420000),
    ("Alatau Arena", "Almaty", 12000, "arena", 200000),
    ("Medeu Hall", "Almaty", 4000, "ginásio", 50000),
    ("Arena Esil", "Astana", 16000, "arena", 260000),
    ("Ala-Too Hall", "Bishkek", 5000, "ginásio", 50000),
    ("Arena Chorsu", "Tashkent", 10000, "arena", 120000),
    ("Varzob Hall", "Duchambé", 4000, "ginásio", 40000),
    ("Arena Alborz", "Teerã", 12000, "arena", 120000),
    ("Yas Island Fight Arena", "Abu Dhabi", 16000, "arena", 900000),
    ("Saadiyat Pavilion", "Abu Dhabi", 6000, "ginásio", 300000),
    ("Creekside Arena", "Dubai", 17000, "arena", 820000),
    ("Diriyah Colosseum", "Riad", 25000, "arena", 1600000),
    ("Kingdom Desert Stadium", "Riad", 60000, "estádio", 4000000),
    ("Lusail Pearl Hall", "Doha", 12000, "arena", 700000),
    ("Muharraq Hall", "Manama", 8000, "ginásio", 260000),
    ("Arena Nilo", "Cairo", 16000, "arena", 180000),
    ("Salle Anfa", "Casablanca", 9000, "ginásio", 110000),
    ("Eko Atlantic Arena", "Lagos", 12000, "arena", 160000),
    ("Palais Mfoundi", "Iaundé", 5000, "ginásio", 50000),
    ("Highveld Dome", "Joanesburgo", 16000, "arena", 220000),
    ("Table Bay Hall", "Cidade do Cabo", 8000, "ginásio", 110000),
    ("Sumida Kokugi Dome", "Tóquio", 11000, "arena", 520000),
    ("Tokyo Bay Arena", "Tóquio", 17000, "arena", 680000),
    ("Kansai Grand Hall", "Osaka", 15000, "arena", 380000),
    ("Saitama Super Dome", "Saitama", 36000, "estádio", 1500000),
    ("Atsuta Hall", "Nagoya", 9000, "ginásio", 160000),
    ("Hakata Bay Arena", "Fukuoka", 10000, "arena", 180000),
    ("Hokkai Dome", "Sapporo", 9000, "ginásio", 150000),
    ("Hangang Arena", "Seul", 15000, "arena", 320000),
    ("Haeundae Hall", "Busan", 8000, "ginásio", 120000),
    ("Huangpu Arena", "Xangai", 18000, "arena", 420000),
    ("Arena Chang'an", "Pequim", 18000, "arena", 400000),
    ("Jinjiang Hall", "Chengdu", 10000, "arena", 180000),
    ("Pearl Delta Arena", "Shenzhen", 16000, "arena", 340000),
    ("Naadam Hall", "Ulan Bator", 5000, "ginásio", 40000),
    ("Pasig River Coliseum", "Manila", 16000, "arena", 220000),
    ("Cordillera Gym", "Baguio", 3000, "clube", 20000),
    ("Chao Phraya Stadium", "Bangkok", 12000, "arena", 200000),
    ("Andaman Fight Arena", "Phuket", 4000, "ginásio", 50000),
    ("Arena Senayan Barat", "Jacarta", 14000, "arena", 200000),
    ("Marina Bay Hall", "Singapura", 12000, "arena", 380000),
    ("Arabian Sea Dome", "Mumbai", 15000, "arena", 260000),
    ("Yamuna Arena", "Nova Délhi", 14000, "arena", 220000),
    ("Harbourside Arena", "Sydney", 21000, "arena", 520000),
    ("Olympic Park Hall", "Sydney", 9000, "ginásio", 180000),
    ("Yarra Park Stadium", "Melbourne", 56000, "estádio", 1600000),
    ("Southbank Arena", "Melbourne", 15000, "arena", 340000),
    ("Moreton Bay Arena", "Brisbane", 13000, "arena", 260000),
    ("Swan River Arena", "Perth", 14000, "arena", 260000),
    ("Torrens Hall", "Adelaide", 9000, "ginásio", 150000),
    ("Waitematā Arena", "Auckland", 12000, "arena", 220000),
    ("Avon Hall", "Christchurch", 7000, "ginásio", 90000),
]

# Camada nacional (Bible §2: 24–30). id, nome, sigla, país, cidade, fundação,
# reputação, alimenta (org global), identidade, situação em 2027
NATIONAL_ORGS = [
    ("nat_rio_kombat", "Rio Kombat Series", "RKS", "BR", "Rio de Janeiro", 2004, 44, "org_vale", "Herdeira do vale-tudo carioca; cards longos e plateia enlouquecida.", "Quer virar a segunda força do Brasil e bater de frente com a Vale."),
    ("nat_nordeste", "Fúria Nordeste Combate", "FNC", "BR", "Recife", 2011, 36, "org_vale", "Prospects nordestinos baratos e agressivos.", "Vive de revelar atletas e vendê-los para fora."),
    ("nat_sul", "Guerreiros do Sul FC", "GSFC", "BR", "Porto Alegre", 2009, 32, "org_crown", "Circuito frio e técnico do Sul; forte em muay thai.", "Patrocinador principal saiu em 2026."),
    ("nat_liberty", "Liberty Fighting Championship", "LFC", "US", "Newark", 2002, 52, "org_crown", "A vitrine clássica da Costa Leste; metade dos campeões Crown passou por aqui.", "Negocia exclusividade de scouting com a Crown."),
    ("nat_lonestar", "Lone Star Cage", "LSC", "US", "Houston", 2008, 46, "org_ascend", "Texas, wrestling universitário e público latino.", "Recebeu aporte de um fundo e quer transmissão nacional."),
    ("nat_midwest", "Midwest Warriors League", "MWL", "US", "Chicago", 2006, 40, "org_ascend", "Wrestlers de universidade virando profissionais.", "Perdeu três campeões para a Ascend em 2026."),
    ("nat_cascade", "Cascade Fight Series", "CFS", "US", "Seattle", 2013, 30, "org_ascend", "Card técnico e produção barata para streaming.", "Opera no vermelho e procura comprador."),
    ("nat_maple", "Maple Cage Series", "MCS", "CA", "Montreal", 2007, 44, "org_crown", "Montreal apaixonada e scouting francófono.", "Quer expandir para Toronto."),
    ("nat_azteca", "Azteca Combate", "AZC", "MX", "Cidade do México", 2010, 48, "org_ascend", "Noites cantadas, boxe agressivo e arenas cheias.", "O maior trunfo do México; recusa virar feeder."),
    ("nat_norte_bravo", "Norte Bravo FC", "NBFC", "MX", "Monterrey", 2014, 34, "org_ascend", "Cardio, pressão e muita trocação.", "Negocia com a Ascend um acordo de desenvolvimento."),
    ("nat_pampa", "Pampa Combate", "PMC", "AR", "Buenos Aires", 2012, 30, "org_vale", "O circuito do Cone Sul; atrai chilenos e uruguaios.", "Sonha com a primeira estrela argentina global."),
    ("nat_andes", "Andes Fighting Championship", "AFC", "PE", "Lima", 2015, 28, "org_vale", "Grapplers peruanos e colombianos.", "Cresce com público digital."),
    ("nat_northern_steel", "Northern Steel FC", "NSFC", "GB", "Newcastle", 2005, 42, "org_frontline", "O norte inglês: striking e cards de fim de semana.", "Tem acordo informal com a Frontline."),
    ("nat_emerald", "Emerald Warriors", "EW", "IE", "Dublin", 2008, 44, "org_frontline", "A promoção que transformou a Irlanda em potência de audiência.", "Quer um evento em estádio."),
    ("nat_ligue_arena", "Ligue Arena Combat", "LAC", "FR", "Paris", 2020, 42, "org_frontline", "Nasceu no dia da liberação do MMA na França.", "Cresce 30% ao ano; atrai capital privado."),
    ("nat_rhein", "Rhein Kampf Serie", "RKS-DE", "DE", "Colônia", 2012, 34, "org_frontline", "Produção de TV alemã impecável e atletas de kickboxing.", "Sobreviveu à proibição televisiva de 2010–2014."),
    ("nat_lowlands", "Lowlands Fight Series", "LFS", "NL", "Amsterdã", 2009, 40, "org_frontline", "Kickboxers holandeses aprendendo a defender queda.", "Disputa talentos com a Frontline."),
    ("nat_nordhavn", "Nordhavn Combat", "NHC", "SE", "Estocolmo", 2011, 30, "org_frontline", "Escandinávia unida num circuito só.", "Busca voltar à TV aberta."),
    ("nat_wisla", "Wisła Fight Arena", "WFA", "PL", "Varsóvia", 2006, 58, "org_frontline", "O fenômeno polonês: estádios cheios e celebridades no card.", "Mais forte que algumas globais em casa; flerta com expansão."),
    ("nat_balkan", "Balkan Warriors League", "BWL", "RS", "Belgrado", 2013, 36, "org_iron", "Kickboxers e wrestlers dos Bálcãs sob uma bandeira só.", "Contratos baratos e atletas duros."),
    ("nat_vltava", "Vltava Fighting", "VF", "CZ", "Praga", 2016, 40, "org_frontline", "A promoção que ensinou a Europa Central a lotar arena.", "Quer comprar uma promotora polonesa."),
    ("nat_taiga", "Taiga Combat Federation", "TCF", "RU", "Moscou", 2003, 52, "org_iron", "A casa histórica do sambo profissional.", "Perde atletas para a Iron Circle e o Oriente Médio."),
    ("nat_kartli", "Kartli Fight Club", "KFC-GE", "GE", "Tbilisi", 2014, 30, "org_iron", "Wrestling e judô georgianos.", "Vende talentos em pacote."),
    ("nat_caspian", "Caspian Fighting", "CAF", "AZ", "Baku", 2012, 38, "org_iron", "Dinheiro do petróleo e arenas modernas.", "Quer sediar um Grand Prix global."),
    ("nat_samarkand", "Samarkand Warrior Series", "SWS", "UZ", "Tashkent", 2015, 32, "org_iron", "Sambo, judô e disciplina.", "Parceria técnica com a Iron Circle."),
    ("nat_anatolia", "Anatolia Savaş Serisi", "ASS", "TR", "Istambul", 2013, 34, "org_frontline", "Wrestling turco e noites de TV.", "Crescimento travado pela moeda fraca."),
    ("nat_genkai", "Genkai Fighting", "GKF", "JP", "Osaka", 1999, 50, "org_shinsei", "Ringue, entradas teatrais e rivalidade eterna com a Shinsei.", "Aceitou virar parceira oficial da Shinsei em 2024."),
    ("nat_hanbit", "Hanbit FC", "HBFC", "KR", "Seul", 2010, 42, "org_shinsei", "Striking coreano e estrelas de internet.", "Negocia streaming com a Ascend."),
    ("nat_jade", "Jade River FC", "JRFC", "CN", "Xangai", 2015, 44, "org_pfl", "Audiência digital gigante e sanda.", "Tem dinheiro, quer legitimidade."),
    ("nat_luzon", "Luzon Warriors FC", "LWFC", "PH", "Manila", 2011, 38, "org_pfl", "Ídolos filipinos de wushu.", "Público fiel, bolsas baixas."),
    ("nat_chao_phraya", "Chao Phraya Fight Night", "CPFN", "TH", "Bangkok", 2014, 36, "org_pfl", "Muay thai com luvas de MMA.", "Atrai estrangeiros dos campos de Phuket."),
    ("nat_southern_cross", "Southern Cross Fight Series", "SCFS", "AU", "Melbourne", 2010, 42, "org_pfl", "Circuito australiano de desenvolvimento.", "Feeder oficial da PFL desde 2019."),
    ("nat_aotearoa", "Aotearoa Fight Series", "AOFS", "NZ", "Auckland", 2012, 36, "org_pfl", "Strikers neozelandeses de elite.", "Quer ser independente da PFL."),
    ("nat_desert_falcon", "Desert Falcon Fighting", "DFF", "AE", "Dubai", 2016, 46, "org_crown", "Garantias altas e noites de gala.", "Paga mais que globais para atrair nomes."),
    ("nat_highveld", "Highveld Fighting Championship", "HFC", "ZA", "Joanesburgo", 2009, 34, "org_crown", "A promoção mais organizada da África.", "Pipeline africano para o mundo."),
    ("nat_lagos", "Lagos Fight Night", "LFN", "NG", "Lagos", 2019, 26, "org_ascend", "Diáspora nigeriana e produção digital.", "Crescimento explosivo, estrutura frágil."),
]

# Organizações extintas: id, nome, sigla, país, cidade, anos, fim, história
DEFUNCT_ORGS = [
    ("def_vtm", "Vale-Tudo Mundial", "VTM", "BR", "Rio de Janeiro", 1991, 1999, "falência",
     "Torneios sem categorias de peso em ginásios lotados. Criou os primeiros mitos brasileiros e morreu com a chegada das regras unificadas."),
    ("def_open_combat", "Open Combat Invitational", "OCI", "US", "Denver", 1993, 2000, "comprada",
     "Torneio de uma noite, estilo contra estilo. Vendida em 2000 a um grupo de cassinos, que a transformou na Crown."),
    ("def_imperial", "Imperial Fighting Federation", "IFF", "JP", "Saitama", 1997, 2008, "escândalo",
     "Megaeventos para 40 mil pessoas e o Grand Prix mais famoso da história. Caiu em 2008 após escândalo de patrocinadores; parte do elenco fundou a era de ouro da Shinsei."),
    ("def_atlantic", "Atlantic Fight League", "AFL", "US", "Atlantic City", 2003, 2011, "comprada",
     "A grande rival americana dos anos 2000. Comprada e absorvida pela Crown em 2011, levando cinco campeões."),
    ("def_samba", "Samba Cage Brasil", "SCB", "BR", "São Paulo", 2006, 2016, "fusão",
     "Promoção paulista de TV aberta. Fundida à Vale Combat em 2016."),
    ("def_neon", "Neon Nights FC", "NNFC", "US", "Las Vegas", 2009, 2013, "falência",
     "Tentou competir com a Crown no próprio quintal pagando bolsas absurdas. Faliu em quatro anos."),
    ("def_kaiser", "Kaiser Kampf Liga", "KKL", "DE", "Hamburgo", 2007, 2012, "proibição",
     "Perdeu a transmissão quando a TV alemã baniu o MMA em 2010 e fechou dois anos depois."),
    ("def_colosseum", "Colosseum Fighting Alliance", "CFA", "IT", "Roma", 2005, 2014, "falência",
     "Galas em ruínas romanas e produção luxuosa, sem receita que pagasse a conta."),
    ("def_eurasia", "Eurasia Combat Union", "ECU", "RU", "São Petersburgo", 2010, 2019, "fusão",
     "Fundiu-se à Iron Circle, que herdou sua biblioteca de lutas e metade do elenco."),
    ("def_pacific_rim", "Pacific Rim Warriors", "PRW", "SG", "Singapura", 2008, 2016, "fusão",
     "Primeira tentativa de liga asiática; incorporada à Pacific Fight League."),
    ("def_monarch", "Monarch MMA", "MON", "US", "Atlanta", 2014, 2020, "pandemia",
     "Volume alto e custo alto. A paralisação de 2020 cortou o caixa e ela não voltou."),
    ("def_riviera", "Riviera Fight Club", "RFC", "MC", "Mônaco", 2018, 2023, "colapso do investidor",
     "Capital privado, bolsas recordes e dívidas escondidas. O calote de 2023 deixou 60 atletas sem receber e é apontado como o estopim da Open Era."),
    ("def_titan_asia", "Great Wall Fighting", "GWF", "CN", "Pequim", 2012, 2018, "regulação",
     "Grande audiência em TV estatal até perder a licença em 2018."),
    ("def_southern_cage", "Southern Cage Circuit", "SCC", "ZA", "Cidade do Cabo", 2004, 2009, "falência",
     "Pioneira africana; seus ex-funcionários fundaram a Highveld FC."),
]

# Eras do universo (Bible §2: 30–35 anos de história)
ERAS = [
    ("era_vale_tudo", 1991, 1999, "A Era do Vale-Tudo",
     "Torneios sem categorias, luvas opcionais e estilo contra estilo. O Brasil exporta o jiu-jitsu, o Japão cria os megaeventos e os EUA descobrem o PPV."),
    ("era_regulation", 2000, 2006, "Regulamentação",
     "As comissões adotam as regras unificadas, surgem as categorias de peso e os rounds. A Crown nasce das cinzas de um torneio de uma noite e aposta tudo em cinturões."),
    ("era_tv_boom", 2007, 2014, "O Boom da TV",
     "Reality shows, TV a cabo e a primeira geração de superestrelas. A Imperial cai, a Shinsei herda o Japão, a Crown engole a Atlantic e a Europa ganha circuitos próprios."),
    ("era_global", 2015, 2021, "Globalização e Streaming",
     "Divisões femininas, streaming, fusões e novas potências: Iron Circle, Pacific Fight League e Ascend. A pandemia de 2020 mata promotoras menores."),
    ("era_rights_crisis", 2022, 2026, "A Crise dos Direitos",
     "Bolsas sobem, o investidor da Riviera dá calote, os contratos de mídia vencem juntos e dezenas de atletas chegam ao fim de contrato ao mesmo tempo."),
    ("era_open", 2027, 2027, "The Open Era",
     "Janeiro de 2027: nenhuma empresa controla o esporte. Mercado aberto, cinturões em disputa e espaço para uma nova promotora."),
]

# Linha do tempo autoral: data, tipo, título, texto, org (opcional)
TIMELINE = [
    ("1991-10-12", "fundacao", "Nasce o Vale-Tudo Mundial", "Primeiro torneio no Rio reúne 8 lutadores de estilos diferentes, sem categorias de peso.", "def_vtm"),
    ("1993-11-20", "fundacao", "Open Combat Invitational em Denver", "Um torneio de uma noite em cadeia de TV fechada apresenta o 'vale-tudo' aos EUA.", "def_open_combat"),
    ("1995-03-04", "marco", "O primeiro PPV", "A OCI vende 86 mil PPVs; os cassinos de Las Vegas prestam atenção.", "def_open_combat"),
    ("1997-07-19", "fundacao", "Fundada a Shinsei", "Tóquio ganha sua própria promoção em ringue, com rounds e tradição de artes marciais.", "org_shinsei"),
    ("1997-10-11", "fundacao", "Imperial Fighting Federation estreia", "40 mil pessoas em Saitama para a primeira noite da IFF.", "def_imperial"),
    ("1999-06-01", "fim", "Fim do Vale-Tudo Mundial", "Sem TV e sem licenças, o VTM encerra atividades.", "def_vtm"),
    ("2000-04-02", "regras", "Regras unificadas", "Comissões dos EUA adotam categorias de peso, rounds de 5 minutos e o critério 10-9.", None),
    ("2000-09-15", "fundacao", "Nasce a Crown Combat", "Um grupo de cassinos compra a OCI e relança a marca como Crown Combat, com cinturões por categoria.", "org_crown"),
    ("2001-03-10", "fundacao", "Vale Combat em São Paulo", "Empresários paulistas criam a Vale Combat para manter os talentos brasileiros em casa.", "org_vale"),
    ("2003-05-24", "fundacao", "Atlantic Fight League", "Atlantic City ganha uma rival direta da Crown.", "def_atlantic"),
    ("2005-04-09", "marco", "Caminho da Coroa", "O reality show da Crown estreia na TV a cabo e cria a primeira geração de fãs casuais.", "org_crown"),
    ("2006-02-18", "fundacao", "Frontline em Londres", "Primeira promoção europeia com produção de nível global.", "org_frontline"),
    ("2007-12-31", "marco", "O Réveillon de Saitama", "A última grande noite da Imperial reúne 48 mil pessoas e o maior público de MMA da história até então.", "def_imperial"),
    ("2008-05-20", "fim", "Queda da Imperial", "Escândalo de patrocinadores derruba a IFF. A Shinsei contrata metade do elenco.", "def_imperial"),
    ("2010-03-01", "regras", "TV alemã bane o MMA", "Emissoras públicas alemãs retiram lutas da grade; o mercado alemão encolhe por quatro anos.", None),
    ("2011-01-15", "fundacao", "Iron Circle em Almaty", "Capital cazaque e treinadores soviéticos fundam a Iron Circle, focada em grappling.", "org_iron"),
    ("2011-06-30", "fusao", "Crown compra a Atlantic", "A maior aquisição da década: cinco campeões e a biblioteca de lutas da AFL passam para a Crown.", "org_crown"),
    ("2012-04-21", "fundacao", "Pacific Fight League", "Sydney vira sede da primeira liga profissional do Pacífico.", "org_pfl"),
    ("2013-02-23", "marco", "Primeira luta feminina valendo cinturão global", "A Crown cria o Galo feminino e lota a arena.", "org_crown"),
    ("2013-09-01", "fim", "Neon Nights fecha", "A promotora que tentou superar a Crown com bolsas milionárias declara falência.", "def_neon"),
    ("2014-08-08", "fundacao", "Ascend Fighting", "Dinheiro de streaming funda a Ascend em Los Angeles, com calendário de volume.", "org_ascend"),
    ("2014-10-01", "regras", "Alemanha libera a TV de novo", "Fim do banimento televisivo; circuitos alemães voltam.", None),
    ("2016-04-14", "regras", "Nova York legaliza o MMA profissional", "Fim de uma batalha legislativa de 20 anos.", None),
    ("2016-07-01", "fusao", "Vale absorve a Samba Cage", "A Vale vira a potência absoluta da América do Sul.", "org_vale"),
    ("2016-11-10", "fusao", "PFL incorpora a Pacific Rim", "Singapura e Sydney sob a mesma bandeira.", "org_pfl"),
    ("2019-03-20", "fusao", "Iron Circle absorve a Eurasia", "Biblioteca e elenco russos passam para Almaty.", "org_iron"),
    ("2020-01-24", "regras", "França libera o MMA", "Último grande mercado europeu a legalizar competições profissionais.", None),
    ("2020-03-15", "crise", "A pausa", "Pandemia paralisa eventos com público por 11 semanas; só quem tinha caixa voltou a lutar em ginásio fechado.", None),
    ("2020-11-30", "fim", "Monarch MMA encerra", "Sem receita de bilheteria, a Monarch não volta da pausa.", "def_monarch"),
    ("2021-08-01", "marco", "Recorde de bolsa", "A Riviera Fight Club paga US$ 12 milhões garantidos a um único atleta.", "def_riviera"),
    ("2022-07-09", "marco", "Carter vs. Mendes I", "Crown 198: cinco rounds, decisão dividida e uma das maiores audiências da história.", "org_crown"),
    ("2023-02-28", "fim", "O calote da Riviera", "O investidor some, 60 atletas ficam sem receber e a confiança no mercado despenca.", "def_riviera"),
    ("2024-06-12", "crise", "Guerra dos direitos", "Crown e Ascend recusam renovar com a TV a cabo; os contratos de mídia globais passam a vencer juntos em dez/2026.", None),
    ("2025-09-03", "crise", "O ano do free agent", "Levantamento da FightMetric: 41% dos atletas ranqueados terão contrato vencendo até jan/2027.", None),
    ("2026-12-31", "marco", "Fim de uma era", "Os contratos de mídia vencem à meia-noite. Começa a Open Era.", None),
]

# Lutas históricas autorais (as geradas pelo builder completam a lista).
# data, org, número do evento, divisão, vermelho, azul, vencedor(red|blue|draw),
# método, round, tempo, estrelas(1-5), título?, tags, história
ANCHOR_FIGHTS = [
    ("2022-07-09", "org_crown", 198, "m_lightweight", "ftr_carter", "hist_mendes", "red", "Decisão dividida", 5, "5:00", 5, True,
     ["classica", "polemica", "recorde_audiencia"],
     "Carter derrubou Mendes no 1º round e sobreviveu a um mata-leão no 4º. Dois juízes deram 48-47 para Carter; um deu para Mendes. O pedido de revanche nunca parou."),
    ("2007-12-31", "def_imperial", 0, "m_heavyweight", "hist_kurogane", "hist_braga", "blue", "Nocaute", 1, "0:38", 5, False,
     ["reveillon", "zebra"],
     "O Réveillon de Saitama: o brasileiro Braga, azarão 7 para 1, nocauteou o ídolo japonês diante de 48 mil pessoas em silêncio."),
    ("2011-06-30", "org_crown", 64, "m_middleweight", "hist_whitfield", "hist_okafor", "red", "Decisão unânime", 5, "5:00", 4, True,
     ["unificacao"],
     "Unificação Crown x Atlantic na noite da compra. Whitfield venceu com wrestling e virou o primeiro campeão unificado."),
]
