#!/usr/bin/env node
/**
 * Build the inline copies of the Overdrive ad runtime.
 *
 *   node tools/build-runtime.js          write go-ads-runtime.min.js and .lean.js
 *   node tools/build-runtime.js --check  fail when the files on disk are stale
 *
 * Source of truth: theme/assets/js/go-ads-runtime.js. Two generated copies:
 *
 *   go-ads-runtime.min.js   full engine + operator surface (logged-in admins)
 *   go-ads-runtime.lean.js  same engine without inspect()/explain() detail
 *                           (every anonymous reader)
 *
 * WHY THIS BUILD REFUSES "<" FOLLOWED BY A LETTER
 *
 * Both copies are printed inline in <head>. Plugins that post-process the final
 * HTML with regular expressions do not know where a <script> starts or ends.
 * Burst Statistics looks for the first "<body" in the document and appends its
 * data-burst_* attributes before the next ">" -- and the previous minified
 * runtime contained `countOccupied(isBodyRecord)<bodyBudget()`, so the plugin
 * wrote `data-burst_id="…"` into the middle of the engine. The inline runtime
 * died with a SyntaxError on every page and ads only started once the footer
 * recovery had downloaded the 150 KB unminified source.
 *
 * So every "<" operator is emitted with a trailing space, and the build fails
 * if any "<" is still followed by a letter, "/", "!" or "?" anywhere in the
 * output (strings and regular expressions included). assets.php refuses to
 * inline a copy that breaks the same rule.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const acorn = require('acorn');
const { minify } = require('terser');

const THEME = path.resolve(__dirname, '..', 'theme');
const SRC = path.join(THEME, 'assets/js/go-ads-runtime.js');
const OUT_FULL = path.join(THEME, 'assets/js/go-ads-runtime.min.js');
const OUT_LEAN = path.join(THEME, 'assets/js/go-ads-runtime.lean.js');
const UNSAFE = /<[A-Za-z!\/?]/;

function leanSource(source) {
  const start = source.indexOf('@lean:strip-start');
  const end = source.indexOf('/* @lean:strip-end */');
  const stubStart = source.indexOf('/* @lean:stub');
  const stubEnd = source.indexOf('@lean:stub-end */');
  if (start < 0 || end < 0 || stubStart < 0 || stubEnd < 0 || !(start < end && end < stubStart && stubStart < stubEnd)) {
    throw new Error('lean markers missing or out of order in go-ads-runtime.js');
  }
  const commentStart = source.lastIndexOf('/*', start);
  const stub = source.slice(stubStart + '/* @lean:stub'.length, stubEnd);
  return source.slice(0, commentStart) + stub + source.slice(stubEnd + '@lean:stub-end */'.length);
}

/* Insert a space after every "<"-family operator that touches the next token. */
function spaceLessThan(code) {
  const tokens = [];
  const tokenizer = acorn.tokenizer(code, { ecmaVersion: 2020, sourceType: 'script' });
  for (const token of tokenizer) tokens.push(token);
  let out = '';
  let cursor = 0;
  for (const token of tokens) {
    const label = token.type.label;
    const value = typeof token.value === 'string' ? token.value : '';
    const isLess = (label === '</>/<=/>=' || label === '<</>>/>>>' || label === '_=') && value.charAt(0) === '<';
    if (!isLess) continue;
    const next = code.charAt(token.end);
    if (next && !/\s/.test(next)) {
      out += code.slice(cursor, token.end) + ' ';
      cursor = token.end;
    }
  }
  return out + code.slice(cursor);
}

async function build(source, version) {
  const result = await minify(source, {
    ecma: 5,
    compress: { passes: 2, keep_fargs: true, pure_getters: false },
    mangle: true,
    format: { comments: false, ascii_only: true, inline_script: true, semicolons: true }
  });
  if (!result.code) throw new Error('terser produced no code');
  let code = spaceLessThan(result.code);
  const banner = '/* Overdrive ad runtime ' + version + ' -- generated by tools/build-runtime.js from go-ads-runtime.js. Do not edit. */\n';
  code = banner + code + '\n';
  const bad = UNSAFE.exec(code);
  if (bad) {
    throw new Error('unsafe "<" sequence in generated runtime near: ' + JSON.stringify(code.slice(Math.max(0, bad.index - 40), bad.index + 40)));
  }
  /* Parse once more; a spacing pass must never change the program. */
  acorn.parse(code, { ecmaVersion: 2020, sourceType: 'script' });
  return code;
}

(async () => {
  const check = process.argv.includes('--check');
  const source = fs.readFileSync(SRC, 'utf8');
  const version = (/var VERSION = '([^']+)'/.exec(source) || [])[1];
  if (!version) throw new Error('VERSION not found in go-ads-runtime.js');
  const full = await build(source, version);
  const lean = await build(leanSource(source), version + ' lean');
  if (check) {
    const stale = [[OUT_FULL, full], [OUT_LEAN, lean]].filter(([file, code]) => !fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== code);
    if (stale.length) {
      console.error('stale generated runtime: ' + stale.map(([file]) => path.basename(file)).join(', ') + ' -- run node tools/build-runtime.js');
      process.exit(1);
    }
    console.log('runtime copies are current (' + version + ')');
    return;
  }
  fs.writeFileSync(OUT_FULL, full);
  fs.writeFileSync(OUT_LEAN, lean);
  /* Generated copies must never look older than their source to assets.php. */
  const now = new Date();
  fs.utimesSync(SRC, now, now);
  fs.utimesSync(OUT_FULL, now, now);
  fs.utimesSync(OUT_LEAN, now, now);
  console.log('built ' + version + ': min ' + full.length + ' bytes, lean ' + lean.length + ' bytes');
})().catch(error => { console.error(error && error.stack || error); process.exit(1); });
